# Generated by Django 3.2.12 on 2022-09-23 09:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('trip_Time', models.TimeField()),
                ('is_Vip', models.BooleanField(default=False)),
                ('cost', models.IntegerField(default=0)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=35)),
                ('counter', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cretaed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('sits_amount', models.IntegerField(default=1)),
                ('total_cost', models.IntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='api.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.BooleanField()),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('public_Number', models.IntegerField(max_length=11, unique=True)),
                ('e_Wallet', models.CharField(max_length=10, unique=True)),
                ('is_Admin', models.BooleanField(default=False)),
                ('is_Charger', models.BooleanField(default=False)),
                ('balance', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
